spring:
  application:
    name: security-05-login-info-printing

  datasource:
    username: root
    password: MyNewP@ssword20250317
    url: jdbc:mysql://localhost:3306/dlyk
    driver-class-name: com.mysql.cj.jdbc.Driver
#
#logging:
#  level:
#    root: debug